---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-ocs
spec:
  selector:
    matchLabels:
      app: mysql-ocs
  serviceName: "mysql-ocs"
  podManagementPolicy: Parallel
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-ocs
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql-ocs
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        resources:
          limits:
            memory: 1Gi
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-ocs-data
          mountPath: /var/lib/mysql
        - name: custom-rh-mysql-config
          mountPath: /etc/mysql/conf.d
      - name: sysbench
        image: vaelinalsorna/sysbench-container:1.2
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: 
              - "bash"
              - "-c"
              - >
                while ! /usr/bin/mysql -sN --user=root --password=password -h $(hostname) -e "select 3" >/dev/null 2>&1 ;
                do
                 /bin/sleep 0.5;
                done;
                log_file=/var/sysbench_log/sysbench-$MY_POD_NAME-$MY_NODE_NAME-$(date +%Y%m%d%H%M%S).log;
                /usr/bin/mysql -sN --user=root --password=password -h $(hostname) -e "create database sysbench";
                /bin/bash ./test1 >> $log_file 2>&1;
                /bin/sleep infinity;
        volumeMounts:
        - name: sysbench-output
          mountPath: /var/sysbench_log
      volumes:
      - name: sysbench-output
        hostPath:
          path: /sysbenchlogs
          type: Directory
      - name: custom-rh-mysql-config
        configMap:
          name: mysql-custom-config
  volumeClaimTemplates:
  - metadata:
      name: mysql-ocs-data
    spec:
      storageClassName: glusterfs-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
