---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-ocs
spec:
  selector:
    matchLabels:
      app: mysql-ocs
  serviceName: "mysql-ocs"
  podManagementPolicy: Parallel
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-ocs
    spec:
      terminationGracePeriodSecods: 10
      containers:
      - name: mysql-ocs
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: secret
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-ocs-data
          mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            tcpSocket:
              port: 3600
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 2
          initialDelaySeconds: 20
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: mysql-ocs-data
    spec:
      storageClassName: gp2
      accessModes: [ "ReadWriteOnce" ]
      persistenVolumeReclaimPolicy: Recycle
      resources:
        requests:
          storage: 8Gi

